// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCfNip4Hgld8QtJOTMb-rh_aeGjQ6Sy7Q',
    appId: '1:13588070021:web:2407106646b694a81873ec',
    messagingSenderId: '13588070021',
    projectId: 'sweaty-44e2d',
    authDomain: 'sweaty-44e2d.firebaseapp.com',
    storageBucket: 'sweaty-44e2d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Gm64HzyaybHPvNwiS6I8-2PuxRPvxwc',
    appId: '1:13588070021:android:8657027fecebe5901873ec',
    messagingSenderId: '13588070021',
    projectId: 'sweaty-44e2d',
    storageBucket: 'sweaty-44e2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcFhkcyx5CdWKj9q6b30VDpRUQHrz87vE',
    appId: '1:13588070021:ios:1966bf40b9f066021873ec',
    messagingSenderId: '13588070021',
    projectId: 'sweaty-44e2d',
    storageBucket: 'sweaty-44e2d.appspot.com',
    iosClientId: '13588070021-dagps7at0m9crgv7hmqi0j368csumuut.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweatCoinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcFhkcyx5CdWKj9q6b30VDpRUQHrz87vE',
    appId: '1:13588070021:ios:ef27c36833ee14691873ec',
    messagingSenderId: '13588070021',
    projectId: 'sweaty-44e2d',
    storageBucket: 'sweaty-44e2d.appspot.com',
    iosClientId: '13588070021-b7gmf0t0tcsqb2n9317l5cn8ma8375ts.apps.googleusercontent.com',
    iosBundleId: 'com.example.sweatCoinApp.RunnerTests',
  );
}
