// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA72ZwNABeytKVEwJ3OGYu-SE-HgJUbN1w',
    appId: '1:433031842032:web:a92df3b6bc8eaa4bdd5a35',
    messagingSenderId: '433031842032',
    projectId: 'sweatcoin-eb203',
    authDomain: 'sweatcoin-eb203.firebaseapp.com',
    storageBucket: 'sweatcoin-eb203.appspot.com',
    measurementId: 'G-C2MF96KDT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-3c4ywfW_56RYr6fS-3uMRQ_v457jEeM',
    appId: '1:433031842032:android:855b527861ceab05dd5a35',
    messagingSenderId: '433031842032',
    projectId: 'sweatcoin-eb203',
    storageBucket: 'sweatcoin-eb203.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2hjqPurRjd7OjJHG_3w-9Pvo6LOUiAQo',
    appId: '1:433031842032:ios:76f6b9e9820c7a94dd5a35',
    messagingSenderId: '433031842032',
    projectId: 'sweatcoin-eb203',
    storageBucket: 'sweatcoin-eb203.appspot.com',
    iosBundleId: 'com.example.sweatcoin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2hjqPurRjd7OjJHG_3w-9Pvo6LOUiAQo',
    appId: '1:433031842032:ios:4be042346e2811e0dd5a35',
    messagingSenderId: '433031842032',
    projectId: 'sweatcoin-eb203',
    storageBucket: 'sweatcoin-eb203.appspot.com',
    iosBundleId: 'com.example.sweatcoin.RunnerTests',
  );
}
